hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path
from room import views
from room.views import UserProfileView,generate_pdf
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
# from room.views import ForgetPassword,ChangePassword
from room.views import available_rooms_for_change,save_profile_picture,get_profile_picture,get_students,before_change_room,noc_form,mess_committee


admin.site.site_header = "HOSTEL Admin"
admin.site.site_title = "HOSTEL Administration Portal"
admin.site.index_title = "Welcome To HOSTEL ADMINISTRATION PANEL"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',views.SignupPage,name='signup'),
    path('',views.LoginPage,name='login'),
    path('home/',views.HomePage,name='home'),
    path('logout/',views.LogoutPage,name='logout'),
    path('menu/', views.menu_page, name='menu_page'),
    path('edit-menu/', views.edit_menu, name='edit_menu'),
    path('feedback_complaint/', views.feedback_complaint_view, name='feedback_complaint'),
    path('feedback_complaint/', views.feedback_complaint_view, name='submit_feedback_complaint'),
 # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),

    path('email_settings/', views.email_settings, name='email_settings'),
    path('user_profile/', UserProfileView.as_view(), name='user_profile'),
    path('save_profile_picture/', save_profile_picture, name='save_profile_picture'),
    path('get_profile_picture/', get_profile_picture, name='get_profile_picture'),

    # path('forget-password/' , ForgetPassword , name="forget_password"),
    # path('change-password/<token>/' , ChangePassword , name="change_password"),

    path('hostel_allotment_registration/', views.hostel_allotment_registration, name='hostel_allotment_registration'),
    path('admin/approve-allotment/<int:registration_id>/', views.approve_allotment_request, name='approve_allotment_request'),
    path('reject_hostel_allotment/<int:registration_id>/', views.reject_hostel_allotment, name='reject_hostel_allotment'),
    path('registration_success/<int:pk>/', views.registration_success, name='registration_success'),
    # path('registration_success/<int:allotment_id>/', views.display_available_rooms, name='registration_success'),
    path('room_details/<int:room_id>/', views.room_details, name='room_details'),
    path('terms_and_conditions/', views.terms_and_conditions, name='terms_and_conditions_page'),



    path('display_available_rooms/<int:allotment_id>/', views.display_available_rooms, name='display_available_rooms'),
    path('room_details/<int:room_id>/', views.room_details, name='room_details'),
    path('change_room/', views.change_room, name='change_room'),
    path('display_available_rooms/', views.display_available_rooms, name='display_available_rooms'),
    path('allot_room/<int:room_id>/', views.allot_room, name='allot_room'),
    path('available_rooms/', views.available_rooms, name='available_rooms'),
    path('available_floors/<int:hostel_id>/', views.available_floors, name='available_floors'),
    path('available_rooms/<int:hostel_id>/<int:floor_number>/', views.available_rooms_on_floor, name='available_rooms_on_floor'),
    path('get_available_floors/<int:hostel_id>/', views.get_available_floors, name='get_available_floors'),
    path('already_allotted/<int:allotment_id>/', views.already_allotted, name='already_allotted'),
    path('hostel/<int:hostel_id>/floor/<int:floor_number>/change/', available_rooms_for_change, name='available_rooms_for_change'),
    path('available_floors_for_change/<int:hostel_id>/', views.available_floors_for_change, name='available_floors_for_change'),
    path('available_rooms_for_change/<int:hostel_id>/<int:floor_number>/', views.available_rooms_for_change, name='available_rooms_for_change'),
    path('before_change_room/', before_change_room, name='before_change_room'),
    path('change-room/approve/<int:request_id>/', views.approved_change_room_request, name='approve_change_room_request'),
    path('change-room/reject/<int:request_id>/', views.reject_change_room_request, name='reject_change_room_request'),
    path('cancel_hostel/', views.cancel_hostel, name='cancel_hostel'),
    path('hostel_details/', views.hostel_details, name='hostel_details'),

    path('hostel/payments/', views.hostel_payments, name='hostel_payments'),
    path('mess/payments/', views.mess_payments, name='mess_payments'),
    path('bill/<int:pk>/', views.bill_detail, name='bill_detail'),
    path('mess-bill-details/<int:mess_payment_id>/', views.mess_bill_details, name='mess_bill_details'),
    path('download_mess_bill/<int:mess_payment_id>/', views.download_mess_bill, name='download_mess_bill'),
    path('notifications/', views.view_notifications, name='notifications'),
    path('notifications/<int:notification_id>/', views.notification_detail, name='notification_detail'),
    path('generate_pdf/<int:bill_id>/', generate_pdf, name='generate_pdf'),
    path('take_attendance/', views.take_attendance, name='take_attendance'),
    path('upload_attendance/', views.upload_attendance, name='upload_attendance'),
    path('edit_attendance/', views.edit_attendance, name='edit_attendance'),
    path('view_attendance/', views.view_attendance, name='view_attendance'),
    path('get_students/', get_students, name='get_students'),
    path('save_attendance/', views.save_attendance, name='save_attendance'),
   # Add a new URL pattern for fetching available hostels
   path('get_available_hostels/', views.get_available_hostels, name='get_available_hostels'),
   path('get_available_floors_for_attendance/<int:hostel_id>/', views.get_available_floors_for_attendance, name='get_available_floors_for_attendance'),
   path('available_students_on_floor/<int:hostel_id>/<int:floor_number>/', views.available_students_on_floor, name='available_students_on_floor'),
   path('noc_form/', noc_form, name='noc_form'),
   path('mess_committee/', mess_committee, name='mess_committee'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/room/urls.py
from django.contrib import admin
from django.urls import path,include
from room import views
from .views import *

urlpatterns = [
    path("", views.SignupPage, name='register'),
    path("login/",views.LoginPage,name='login'),
    path('logout/',views.LogoutPage,name='logout'),
]

hotel/room/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.urls import reverse 

class CustomUserManager(BaseUserManager):
    def create_user(self, registration_number, email, phone, password=None, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')

        email = self.normalize_email(email)
        user = self.model(registration_number=registration_number, email=email, phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, registration_number, email, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(registration_number, email, phone, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    registration_number = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    phone = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(1000000000), MaxValueValidator(9999999999)])
    date_joined = models.DateTimeField(default=timezone.now)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    date = models.DateTimeField(default=timezone.now)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)

    objects = CustomUserManager()

    # Updated the USERNAME_FIELD to allow login with either email or registration_number
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['registration_number', 'phone']  # Include other required fields

    def clean(self):
        if not str(self.phone).isdigit():
            raise ValidationError('Phone number must contain only numeric digits.')

    def __str__(self):
        return self.registration_number

    def get_full_name(self):
        return self.registration_number

    def get_short_name(self):
        return self.registration_number

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

class Hostel(models.Model):
    name = models.CharField(max_length=50, unique=True)
    capacity = models.IntegerField(default=300)  # Set the capacity of each hostel to 300

    def __str__(self):
        return self.name
    

    def create_rooms(self):
        for floor_number in range(1, 5):
            for room_number in range(1, 31):
                room = HostelRoom.objects.create(
                    hostel=self,
                    floor_number=floor_number,
                    room_number=room_number,
                    capacity=3  # Default capacity for regular students
                )
                if self.name.startswith("GH") or self.name.startswith("BH"):
                    room.capacity = 2  # Capacity for PhD students
                room.save()
    
    def get_remaining_capacity(self):
        total_allotments = self.allotments.count()
        remaining_capacity = self.capacity - total_allotments
        return remaining_capacity

    def get_total_rooms(self):
        return self.rooms.count()

    def get_total_allotments(self):
        return self.allotments.count()  # Use the related name 'allotments'



    def get_vacancies(self):
        return self.capacity - self.get_total_allotments()

# Hostel Room Model
class HostelRoom(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.SET_NULL, null=True)
    floor_number = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 5)], default=1)  # Floors 1 to 4
    room_number = models.PositiveIntegerField()
    capacity = models.IntegerField(default=3)  # Total capacity of the room (3 beds by default)
    is_phd_only = models.BooleanField(default=False)  # True if only one student is allowed (for PhD scholars)

    def __str__(self):
        return f"{self.hostel.name} - Floor {self.floor_number} - Room {self.room_number}"
    def get_vacancies(self):
        # If PhD student is in the room, vacancy is 2; otherwise, it's the default capacity (3).
        if self.is_phd_only:
            return 2
        return self.capacity

# Hostel Allotment Registration Model
class HostelAllotmentRegistration(models.Model):
    # Foreign keys to collect data from the CustomUser model
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
      # New field for full name
    full_name = models.CharField(max_length=200,null=True)  # You can adjust the max_length as needed
    father_name = models.CharField(max_length=200,null=True)
    registration_number = models.CharField(max_length=20, blank=True)
    email = models.EmailField(max_length=255, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    date_of_birth = models.DateField(null=True, default=None)
    terms_and_conditions = models.BooleanField(default=False)
   

    # Other fields for the registration form
    department = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    semester = models.CharField(max_length=100)
    religion = models.CharField(max_length=50)
    district = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('others', 'Others'),
    )
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    allotted_date = models.DateTimeField(default=timezone.now)  # Add the allotted_date field
    is_canceled = models.BooleanField(default=False)  # Add this field for cancellation status

    allotted_hostel = models.ForeignKey(Hostel, on_delete=models.SET_NULL, null=True, blank=True, related_name='allotments')
    allotted_room = models.ForeignKey(HostelRoom, on_delete=models.SET_NULL, null=True, blank=True)
    # Add an approval field to track the allotment request approval status
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.registration_number} - {self.department} - {self.semester}"

    def is_phd_scholar(self):
        return self.course == 'PHD'

    def can_be_added_to_room_with_phd_scholar(self, room):
        if not room.is_phd_only:
            return True
        return self.is_phd_scholar() and HostelAllotmentRegistration.objects.filter(allotted_room=room).count() == 1
    

class ChangeRoomRequest(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200, null=True)
    registration_number = models.CharField(max_length=20, blank=True)
    email = models.EmailField(max_length=255, blank=True)
    current_hostel = models.ForeignKey(Hostel, on_delete=models.SET_NULL, null=True, blank=True)
    current_room_number = models.CharField(max_length=10, blank=True)
    application_reason = models.TextField()
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.registration_number} - {self.full_name}"


class Bill(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)  # Change this to match your Student model
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    months_stayed = models.PositiveIntegerField(default=0)
    generated_date = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)
    receipt_number = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return f"{self.student.registration_number} - {self.amount}"

    def generate_receipt_number(self):
        today = datetime.datetime.now()
        date_part = today.strftime('%d%m%Y')
        counter_part = str(ReceiptNumberCounter.objects.first().get_next_receipt_number()).zfill(2)
        return date_part + counter_part

    def save(self, *args, **kwargs):
        if not self.receipt_number:
            self.receipt_number = self.generate_receipt_number()
        super().save(*args, **kwargs)


class ReceiptNumberCounter(models.Model):
    counter = models.PositiveIntegerField(default=1)

    def get_next_receipt_number(self):
        next_receipt_number = self.counter
        self.counter += 1
        self.save()
        return next_receipt_number

    class Meta:
        verbose_name_plural = 'Receipt Number Counters'


class MessPayment(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    months_name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    generated_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)  # To mark if the bill is paid
    receipt_number = models.CharField(max_length=20, unique=True, blank=True, null=True)

    def __str__(self):
        return f"{self.student.registration_number} - {self.months_name}"

    def generate_receipt_number(self):
        today = datetime.datetime.now()

hotel/templates/available_floors.html
<!-- available_floors.html -->
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% include 'messages.html' %} 
{% block content %}
  <h2>Available Floors in {{ hostel.name }}</h2>
  <ul>
    {% for floor in floors %}
      <li><a href="{% url 'available_rooms_on_floor' hostel.id floor %}">Floor {{ floor }}</a></li>
    {% endfor %}
  </ul>
  <style>
    body {
      background-color: #f5f5f5;
      font-family: 'Arial', sans-serif;
      margin: 0; /* Remove default body margin */
    }

    h2 {
      font-size: 28px;
      font-weight: bold;
      color: black;
      color: linear-gradient(135deg, #71b7e6, #9b59b6);
      margin: 10px 0 20px; /* Adjust margin */
      position: relative;
    }

    /* Add an underline under the container title */
    h2::before {
      content: "";
      position: absolute;
      left: 38%;
      transform: translateX(-50%);
      bottom: 0;
      height: 3px;
      width: 125px;
      background: linear-gradient(135deg, #0056b3, #fc8003);
    }

    ul {
      list-style: none;
      padding: 0;
      margin: 0; /* Remove default margin */
    }

    li {
      display: block; /* Display each floor in a new line */
      margin: 0 auto 15px auto; /* Center each box horizontally and add bottom margin */
      padding: 20px;
      border: 2px solid #ddd;
      border-radius: 5px;
      background-color: #d8d7d7;
      transition: transform 0.2s ease-in-out;
      width: 60%; /* Make each box 80% width of the container */
      box-sizing: border-box; /* Include padding and border in box sizing */
      font-size: 20px; /* Increase the font size */
      font-weight: bold; /* Make the text bold */
      text-align: center; /* Center the text inside the box */
    }

    li:hover {
      transform: scale(1.05);
    }
  </style>
{% endblock %}

hotel/templates/available_rooms.html
{% extends 'base.html' %}
{% include 'messages.html' %} 
{% block content %}
  <h1>Available Rooms</h1>
  {% include 'messages.html' %} 
  {% if available_rooms %}
    <p>Debug: Number of available rooms: {{ available_rooms|length }}</p>
    <ul>
      {% for room in available_rooms %}
        <li>
          Room: {{ room.floor_number }}{{ room.room_number }}
          <a href="{% url 'room_details' room.id %}">(Details)</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Debug: No available rooms</p>
    <p>No available rooms in your allotted hostel.</p>
  {% endif %}
  
  <p><a href="{% url 'change_room' %}">Change Room</a></p>
{% endblock %}




{% comment %} {% block content %}
  <h1>Available Rooms</h1>
  {% if available_rooms %}
    <ul>
      {% for room in available_rooms %}
        <li>
          Room: {{ room.floor_number }}{{ room.room_number }}
          <a href="{% url 'room_details' room.id %}">(Details)</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No available rooms in your allotted hostel.</p>
  {% endif %}
  <p><a href="{% url 'change_room' %}">Change Room</a></p>
{% endblock %}  {% endcomment %}


{% comment %} <!-- available_rooms.html -->
{% extends 'base.html' %}
{% block content %}
  {% if allotment %}
    <h2>Your Allotment Details</h2>
    <!-- Display user's allotment details here -->
    Allotted Hostel: {{ allotment.allotted_hostel.name }}<br>
    Allotted Room: {{ allotment.allotted_room.floor_number }}{{ allotment.allotted_room.room_number }}<br>
    <!-- Add more details as needed -->
    <br>
    <h2>Available Rooms</h2>
    <ul>
      {% for room in available_rooms %}
        <li>
          Room {{ room.floor_number }}{{ room.room_number }}
          {% if room.capacity - room.hostelallotmentregistration_set.count() > 0 %}
          (<a href="{% url 'change_room' room.id %}">Change Room</a>)

            {% comment %}
              (<a href="{% url 'change_room' %}">Change Room</a>)
            
          {% else %}
            (Full)
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>You have not been allotted a hostel.</p>
  {% endif %}
{% endblock %} {% endcomment %}





{% comment %} {% extends 'base.html' %}

{% block content %}
  <h1>Available Rooms</h1>
  {% if available_rooms %}
    <ul>
      {% for room in available_rooms %}
        <li>
          Room: {{ room.floor_number }}{{ room.room_number }}
          <a href="{% url 'room_details' room.id %}">(Details)</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No available rooms in your allotted hostel.</p>
  {% endif %}
  <p><a href="{% url 'change_room' %}">Change Room</a></p>
{% endblock %} {% endcomment %}

<!-- available_rooms.html -->

<!-- available_rooms.html -->



{% comment %} {% extends 'base.html' %}

{% block content %}
  <h1>Available Rooms</h1>
  <p>Welcome, {{ allotment.student.registration_number }}!</p>
  
  <h2>Your Allotment Details</h2>
  <p>Hostel: {{ allotment.allotted_hostel.name }}</p>
  <p>Room: {% if allotment.allotted_room %}{{ allotment.allotted_room.room_number }}{% else %}Not Allotted{% endif %}</p>

  <h2>Available Rooms</h2>
  <ul>
    {% for room in available_rooms %}
      <li>
        {% if room == allotment.allotted_room %}
          <strong>{{ room.hostel.name }} - Room {{ room.room_number }} (Your Current Room)</strong>
        {% else %}
          {{ room.hostel.name }} - Room {{ room.room_number }} (Capacity: {{ room.capacity }})
          <form method="post" action="{% url 'allot_room' room.id %}">
            {% csrf_token %}
            <button type="submit">Allot Room</button>
          </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}
 {% endcomment %}

hotel/templates/change_room.html
{% extends 'base.html' %}
{% block content %}
  {% if allotment %}
    <h2>Your Allotment Details</h2>
    Allotted Hostel: {{ allotment.allotted_hostel.name }}<br>
    Allotted Room: {{ allotment.allotted_room.floor_number }}{{ allotment.allotted_room.room_number }}<br>
    <br>
    {% if allotment.allotted_room %}
      <h2>Change Room</h2>
      <form method="post">
        {% csrf_token %}
        <select name="new_room">
          <option value="" selected disabled>Select a new room</option>
          {% for room in allotment.allotted_hostel.hostelroom_set.all %}
            {% if room.capacity > room.hostelallotmentregistration_set.count and room != allotment.allotted_room %}
              <option value="{{ room.id }}">Room {{ room.floor_number }}{{ room.room_number }}</option>
            {% endif %}
          {% endfor %}
        </select>
        <button type="submit">Change Room</button>
      </form>
    {% endif %}
  {% else %}
    <p>You have not been allotted a hostel.</p>
  {% endif %}
{% endblock %}



{% comment %} {% extends 'base.html' %}
{% block content %}
  {% if allotment %}
    <h2>Your Allotment Details</h2>
    Allotted Hostel: {{ allotment.allotted_hostel.name }}<br>
    Allotted Room: {{ allotment.allotted_room.floor_number }}{{ allotment.allotted_room.room_number }}<br>
    <br>
    {% if available_floors %}
      <h2>Available Floors for Room Change</h2>
      <ul>
        {% for floor in available_floors %}
          <li>
            <a href="{% url 'available_rooms_on_floor' allotment.allotted_hostel.id floor.floor_number %}">
              Floor {{ floor.floor_number }}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No available floors for room change.</p>
    {% endif %}
  {% else %}
    <p>You have not been allotted a hostel.</p>
  {% endif %}
{% endblock %} {% endcomment %}


{% comment %} {% extends 'base.html' %}
{% block content %}
  {% if allotment %}
    <h2>Your Allotment Details</h2>
    <!-- Display user's allotment details here -->
    Allotted Hostel: {{ allotment.allotted_hostel.name }}<br>
    Allotted Room: {{ allotment.allotted_room.floor_number }}{{ allotment.allotted_room.room_number }}<br>
    <!-- Add more details as needed -->
    <br>
    <p><a href="{% url 'available_floors' allotment.allotted_hostel.id %}">View Available Floors</a></p>
    <h2>Available Rooms for Room Change</h2>
    <ul>
      {% for room in available_rooms %}
        <li>
          Room {{ room.floor_number }}{{ room.room_number }}
          {% if room.capacity > room.hostelallotmentregistration_set.count %}
            (<a href="#" onclick="showConfirmationModal('{{ room.id }}')">Change Room</a>)
          {% else %}
            (Full)
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>You have not been allotted a hostel.</p>
  {% endif %}

  <!-- Confirmation Modal -->
  <div id="confirmationModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirm Room Change</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to change your room?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form id="change-room-form" action="{% url 'change_room' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="new_room" id="new_room_input">
            <button type="submit" class="btn btn-primary">Change Room</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    function showConfirmationModal(roomId) {
      const confirmationModal = document.getElementById('confirmationModal');
      const newRoomInput = document.getElementById('new_room_input');

      newRoomInput.value = roomId;
      $(confirmationModal).modal('show');
    }
  </script>
{% endblock %} {% endcomment %}





{% comment %} {% extends 'base.html' %}

{% block content %}
  <h1>Change Room</h1>
  <p>Your current room: {{ allotment.allotted_room.floor_number }}{{ allotment.allotted_room.room_number }}</p>
  <h2>Available Rooms:</h2>
  <form method="post">
    {% csrf_token %}
    <select name="new_room">
      {% for room in available_rooms %}
        {% if room.capacity - allotment.allotted_room.allotmentregistration_set.count() > 0 %}
          <option value="{{ room.id }}">Room: {{ room.floor_number }}{{ room.room_number }}</option>
        {% endif %}
      {% endfor %}
    </select>
    <button type="submit">Change Room</button>
  </form>
  <p><a href="{% url 'display_available_rooms' allotment.id %}">Back to Available Rooms</a></p>
{% endblock %} {% endcomment %}

hotel/templates/user_profile.html
<!-- User Details Container -->
<div class="user-details">
    <!-- Display User Name and Registration Number -->
    <p>Name: {{ user.name }}</p>
    <p>Registration Number: {{ user.registration_number }}</p>

    <!-- Change Password Link -->
    <a href="{% url 'password_change' %}">Change Password</a>

    <!-- Logout Link -->
    <a href="{% url 'logout' %}">Logout</a>
</div>